#!/usr/bin/env node
// Guide catalog build: inlines guides/topics/*.md into
// src/guides/catalog.generated.ts and derives the GuideTopic union from the
// filenames. The Markdown files are the single source; the generated module
// exists because the published bundle has no filesystem view of the package
// (tsdown defines import.meta as {}) and single-file distribution must carry
// the topics. `--check` fails when the generated file is stale.
//
// Usage: node scripts/guides.mjs            (write)
//        node scripts/guides.mjs --check    (verify only)
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, relative } from "node:path"
import { execTool, repoRoot, requireToolchain } from "./lib/toolchain.mjs"

const TOPIC_DIR = join(repoRoot, "guides", "topics")
const TARGET = join(repoRoot, "src", "guides", "catalog.generated.ts")
const check = process.argv.includes("--check")

const fail = (message) => {
  process.stderr.write(`${message}\n`)
  process.exit(1)
}

/** Frontmatter: `---\nkey: value\n---\n\n` then Markdown. Keys are single-line. */
const parseTopic = (file, raw) => {
  const source = raw.replaceAll("\r\n", "\n")
  const match = source.match(/^---\n([\s\S]*?)\n---\n\n([\s\S]*?)\n?$/)
  if (match === null)
    fail(`${file}: expected frontmatter (--- … ---) followed by a blank line and Markdown`)
  const meta = {}
  for (const line of match[1].split("\n")) {
    const at = line.indexOf(":")
    if (at < 1) fail(`${file}: invalid frontmatter line ${JSON.stringify(line)}`)
    const key = line.slice(0, at).trim()
    if (key in meta) fail(`${file}: duplicate frontmatter key ${key}`)
    meta[key] = line.slice(at + 1).trim()
  }
  // The complete topic contract. Which commands a topic covers is declared by
  // the CommandContracts (guides: [...]), never here: one owner per fact.
  for (const key of Object.keys(meta)) {
    if (!["topic", "title", "brief"].includes(key)) {
      fail(`${file}: unknown frontmatter key "${key}" (allowed: topic, title, brief)`)
    }
  }
  for (const key of ["topic", "title", "brief"]) {
    if (!meta[key]) fail(`${file}: missing frontmatter key "${key}"`)
  }
  if (!/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/.test(meta.topic)) fail(`${file}: topic must be kebab-case`)
  if (file !== `${meta.topic}.md`) fail(`${file}: filename must be ${meta.topic}.md`)
  const content = match[2].trim()
  const bytes = Buffer.byteLength(content, "utf8")
  if (bytes === 0 || bytes > 12_000) {
    fail(
      `${file}: body must be nonempty and at most 12000 UTF-8 bytes (a model, sized for an agent's context)`,
    )
  }
  if (!content.startsWith("# ")) fail(`${file}: body must start with a level-one heading`)
  return { topic: meta.topic, title: meta.title, brief: meta.brief, content }
}

const topics = (existsSync(TOPIC_DIR) ? readdirSync(TOPIC_DIR) : [])
  .filter((file) => file.endsWith(".md"))
  .toSorted()
  .map((file) => parseTopic(file, readFileSync(join(TOPIC_DIR, file), "utf8")))
if (new Set(topics.map((t) => t.topic)).size !== topics.length) fail("guide topics must be unique")

const literal = (value) => JSON.stringify(value)
const body = `// GENERATED by scripts/guides.mjs from guides/topics/*.md — do not edit.
// Edit the Markdown, then run: node scripts/guides.mjs
// npm run check fails when this file is stale.

export interface GuideEntry {
  readonly topic: string
  readonly title: string
  /** One-to-three sentence "read this when…" synopsis, served by \`guide get <topic> --brief\`. */
  readonly brief: string
  readonly content: string
}

export type GuideTopic = ${topics.map((t) => literal(t.topic)).join(" | ") || "never"}

export const GUIDE_TOPICS: ReadonlyArray<GuideEntry & { readonly topic: GuideTopic }> = [
${topics
  .map(
    (t) => `  {
    topic: ${literal(t.topic)},
    title: ${literal(t.title)},
    brief: ${literal(t.brief)},
    content: ${literal(t.content)},
  },`,
  )
  .join("\n")}
]
`

requireToolchain()
// Biome owns formatting; format the candidate in memory-equivalent fashion by
// writing to the target only when it changed, then formatting in place.
const current = existsSync(TARGET) ? readFileSync(TARGET, "utf8") : undefined
if (check) {
  if (current === undefined)
    fail(`${relative(repoRoot, TARGET)} is missing; run: node scripts/guides.mjs`)
  // Compare against a freshly generated candidate, formatted in a temp dir so
  // --check never writes inside the repository.
  const dir = mkdtempSync(join(tmpdir(), "lasso-guides-"))
  const candidate = join(dir, "catalog.generated.ts")
  writeFileSync(candidate, body)
  try {
    execTool("biome", ["format", "--write", candidate], { stdio: "ignore" })
    if (readFileSync(candidate, "utf8") !== current) {
      fail(`${relative(repoRoot, TARGET)} is stale; run: node scripts/guides.mjs`)
    }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
  process.stderr.write(`guide catalog current (${topics.length} topics)\n`)
} else {
  writeFileSync(TARGET, body)
  execTool("biome", ["format", "--write", TARGET], { stdio: "ignore" })
  process.stderr.write(`wrote ${relative(repoRoot, TARGET)} (${topics.length} topics)\n`)
}
